import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#00504a",
        "error-container": "#ffdad6",
        "on-background": "#131b2e",
        "surface-container-low": "#f2f3ff",
        "outline": "#6e7977",
        "on-tertiary": "#ffffff",
        "surface": "#faf8ff",
        "tertiary-fixed": "#85f8c4",
        "error": "#ba1a1a",
        "tertiary": "#005e40",
        "background": "#faf8ff",
        "inverse-primary": "#80d5cb",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "on-secondary": "#ffffff",
        "outline-variant": "#bdc9c6",
        "primary": "#005c55",
        "on-tertiary-container": "#99ffce",
        "secondary": "#4648d4",
        "primary-container": "#0f766e",
        "on-primary-container": "#a3faef",
        "tertiary-container": "#007954",
        "surface-container-highest": "#dae2fd",
        "on-tertiary-fixed": "#002114",
        "on-secondary-fixed": "#07006c",
        "inverse-on-surface": "#eef0ff",
        "primary-fixed-dim": "#80d5cb",
        "surface-tint": "#006a63",
        "secondary-fixed-dim": "#c0c1ff",
        "surface-container": "#eaedff",
        "surface-variant": "#dae2fd",
        "tertiary-fixed-dim": "#68dba9",
        "on-tertiary-fixed-variant": "#005137",
        "on-surface-variant": "#3e4947",
        "inverse-surface": "#283044",
        "primary-fixed": "#9cf2e8",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#00201d",
        "surface-container-high": "#e2e7ff",
        "secondary-container": "#6063ee",
        "on-surface": "#131b2e",
        "on-secondary-container": "#fffbff",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "secondary-fixed": "#e1e0ff",
        clinical: {
          50: "#f0fdfa",
          100: "#ccfbf1",
          200: "#99f6e4",
          500: "#14b8a6",
          600: "#0d9488",
          700: "#0f766e",
          800: "#115e59",
          900: "#134e4a",
          950: "#042f2e",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "2rem",
        "space-xl": "2rem",
        "gutter-desktop": "1.5rem",
        gutter: "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.875rem",
        margin: "1rem",
      },
      fontFamily: {
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-code-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "label-code-lg": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "36px",
          {
            lineHeight: "44px",
            letterSpacing: "-0.025em",
            fontWeight: "600",
          },
        ],
        "headline-lg-mobile": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.015em",
            fontWeight: "600",
          },
        ],
        "headline-md": [
          "20px",
          {
            lineHeight: "28px",
            letterSpacing: "-0.015em",
            fontWeight: "600",
          },
        ],
        "headline-lg": [
          "28px",
          {
            lineHeight: "36px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "body-sm": [
          "12px",
          {
            lineHeight: "18px",
            letterSpacing: "0.005em",
            fontWeight: "400",
          },
        ],
        "label-code-sm": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0em",
            fontWeight: "500",
          },
        ],
        "label-caps": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "headline-sm": [
          "16px",
          {
            lineHeight: "24px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "label-code-lg": [
          "13px",
          {
            lineHeight: "18px",
            letterSpacing: "-0.01em",
            fontWeight: "500",
          },
        ],
        "body-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0em",
            fontWeight: "400",
          },
        ],
        "body-lg": [
          "16px",
          {
            lineHeight: "24px",
            letterSpacing: "-0.005em",
            fontWeight: "400",
          },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
